#!/data/data/com.termux/files/usr/bin/bash -e

rm -f kali-khanhnguyenup.sh

VERSION=20211224
USERNAME="kali"

function ask() {
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        printf "${light_cyan}\n[?] "
        read -p "$1 [$prompt] " REPLY

        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        printf "${reset}"

        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

function get_arch() {
    printf "${blue}[*] Kiem tra CPU...."
    case $(getprop ro.product.cpu.abi) in
        arm64-v8a)
            SYS_ARCH=arm64
			printf " ARCH: $(getprop ro.product.cpu.abi) (aarch64)"
            ;;
        armeabi|armeabi-v7a)
			printf " ARCH: $(getprop ro.product.cpu.abi) (armhf)"
			printf " @ Unsupported CPU"
			exit 1
            ;;
        *)
			printf " ARCH: $(getprop ro.product.cpu.abi) (unknown))"
			printf "\n\n\n @ Unsupported CPU \n\n"
			exit 1
            ;;
    esac
}

function set_strings() {
    CHROOT=kali-arm64
    IMAGE_NAME=kali-arm64-khanhnguyen.tar.xz
    SHA_NAME=kali-arm64-khanhnguyen.sha512sum
}    

function prepare_fs() {
    unset KEEP_CHROOT
    if [ -d ${CHROOT} ]; then
    	printf " - Phat hien Kali-linux da duoc cai dat \n"
        if ask " Ban co muon xoa tat ca data va cai lai khong?" "Y"; then
            rm -rf ${CHROOT}
        else
            exit 1
        fi
    fi
} 

function cleanup() {
    if [ -f ${IMAGE_NAME} ]; then
		rm -f ${IMAGE_NAME}
        rm -f ${SHA_NAME}
		printf " - Da cai dat xong!"
    fi
} 

function check_dependencies() {
    printf "${blue}\n[*] Dang kiem tra....${reset}\n"
    apt-get update -y &> /dev/null || apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" dist-upgrade -y &> /dev/null
    apt-get upgrade -y &> /dev/null
    printf "${blue}[*] - Done ${reset}\n"
}


function get_url() {
    ROOTFS_URL="https://tinyurl.com/nx64mce5"
    SHA_URL="https://tinyurl.com/xb7jsx2x"
}

function get_rootfs() {
    unset KEEP_IMAGE
    if [ -f ${IMAGE_NAME} ]; then
        rm -f ${IMAGE_NAME}
    fi
    printf "${blue}[*] Dang tai Kali-Linux (arm64)...."
    printf " (1.71GB)${reset}\n\n"
    get_url
    wget -O kali-arm64-khanhnguyen.tar.xz "$ROOTFS_URL" && echo "- Get success"
}

function get_sha() {
    if [ -f ${SHA_NAME} ]; then
		rm -f ${SHA_NAME}
    fi
    wget -O kali-arm64-khanhnguyen.sha512sum "${SHA_URL}" 2> /dev/null
}

function verify_sha() {
	clear
	printf "${blue}##################################################\n"
	printf "${blue}##                                              ##\n"
	printf "${blue}##  88      a8P         db        88        88  ##\n"
	printf "${blue}##  88    .88'         d88b       88        88  ##\n"
	printf "${blue}##  88   88'          d8''8b      88        88  ##\n"
	printf "${blue}##  88 d88           d8'  '8b     88        88  ##\n"
	printf "${blue}##  8888'88.        d8YaaaaY8b    88        88  ##\n"
	printf "${blue}##  88P   Y8b      d8''''''''8b   88        88  ##\n"
	printf "${blue}##  88     '88.   d8'        '8b  88        88  ##\n"
	printf "${blue}##  88       Y8b d8'          '8b 888888888 88  ##\n"
	printf "${blue}##                                              ##\n"
	printf "${blue}##                 arm64-v8a by KhanhNguyen9872 ##\n"
	printf "${blue}##################################################${reset}\n\n"
        printf "\n${blue}[*] Dang kiem tra file cai dat....${reset}\n"
        sha512sum -c $SHA_NAME || {
            printf "${red} File cai dat bi hong. Vui long cai lai \n${reset}"
	    rm -f $SHA_NAME 2> /dev/null
	    rm -f $IMAGE_NAME 2> /dev/null
	    rm -f install-kali-khanhnguyen 2> /dev/null
	    rm -f update-kali-khanhnguyen 2> /dev/null
            exit 1
        }
	rm -f $SHA_NAME
}

function extract_rootfs() {
        printf "\n${blue}[*] Dang cai dat Kali-Linux (arm64).... ${reset}\n"
		printf "\n${blue}    @@ Qua trinh co the mat kha nhieu thoi gian @@ ${reset}\n"
		printf "\n${red}             @@ Tam 5-15 phut @@ ${reset}\n\n"
        	proot --link2symlink tar -xJf $IMAGE_NAME 2> /dev/null || :
		rm -f $IMAGE_NAME
		wget -O recovery https://tinyurl.com/542f74rn 2> /dev/null && echo "- Installing Recovery..."
		wget -O version https://tinyurl.com/53n7htrn 2> /dev/null && echo "- Updating version..."
		wget -O versionrecovery https://tinyurl.com/fvcj5463 2> /dev/null && echo "- Updating version recovery..."
		mv recovery ${PREFIX}/bin/recovery 2> /dev/null
		chmod 777 ${PREFIX}/bin/recovery 2> /dev/null
		mv version ${PREFIX}/bin/version 2> /dev/null
		chmod 777 ${PREFIX}/bin/version 2> /dev/null
		mv versionrecovery ${PREFIX}/bin/versionrecovery 2> /dev/null
		chmod 777 ${PREFIX}/bin/versionrecovery 2> /dev/null
		echo 'update_enable' > ${PREFIX}/bin/settingsupdate 2> /dev/null
		echo 'update_enable' > ${PREFIX}/bin/settingsupdatekali 2> /dev/null
		chmod 777 ${PREFIX}/bin/settingsupdate 2> /dev/null
		chmod 777 ${PREFIX}/bin/settingsupdatekali 2> /dev/null
}


function create_launcher() {
    KH_RECOVERY=$HOME/kali-arm64/usr/bin/recovery
    NH_LAUNCHER=${PREFIX}/bin/kali
    NH_SHORTCUT=${PREFIX}/bin/nh
    KEX_LAUNCHER=$HOME/kali-arm64/usr/bin/khanh
    wget -O kali https://raw.githubusercontent.com/KhanhNguyen9872/Kali-Linux-aarch64-arm64-/main/kali
    mv kali ${PREFIX}/bin/kali
    chmod 777 ${PREFIX}/bin/kali
	
	cat > $KH_RECOVERY <<- EOF
##!/data/data/com.termux/files/usr/bin/bash -e
red='\033[1;31m'
printf "%b\n" "${red}\n Please exit Kali-Linux and run 'recovery' in Termux \n\n"
	EOF

    chmod 777 $NH_LAUNCHER
    chmod 777 $KH_RECOVERY
    chmod 777 $KEX_LAUNCHER
    if [ -L ${NH_SHORTCUT} ]; then
        rm -f ${NH_SHORTCUT}
    fi
    if [ ! -f ${NH_SHORTCUT} ]; then
        ln -s ${NH_LAUNCHER} ${NH_SHORTCUT} >/dev/null
    fi
}

function fix_profile_bash() {
    if [ -f ${CHROOT}/root/.bash_profile ]; then
        sed -i '/if/,/fi/d' "${CHROOT}/root/.bash_profile"
    fi
}

function fix_sudo() {
    chmod +s $CHROOT/usr/bin/sudo
    chmod +s $CHROOT/usr/bin/su
	echo "kali    ALL=(ALL:ALL) ALL" > $CHROOT/etc/sudoers.d/kali

    echo "Set disable_coredump false" > $CHROOT/etc/sudo.conf
}

function fix_uid() {
    USRID=$(id -u)
    GRPID=$(id -g)
    nh -r usermod -u $USRID kali 2>/dev/null
    nh -r groupmod -g $GRPID kali 2>/dev/null
}

function print_banner() {
    clear
    printf "${blue}##################################################\n"
    printf "${blue}##                                              ##\n"
    printf "${blue}##  88      a8P         db        88        88  ##\n"
    printf "${blue}##  88    .88'         d88b       88        88  ##\n"
    printf "${blue}##  88   88'          d8''8b      88        88  ##\n"
    printf "${blue}##  88 d88           d8'  '8b     88        88  ##\n"
    printf "${blue}##  8888'88.        d8YaaaaY8b    88        88  ##\n"
    printf "${blue}##  88P   Y8b      d8''''''''8b   88        88  ##\n"
    printf "${blue}##  88     '88.   d8'        '8b  88        88  ##\n"
    printf "${blue}##  88       Y8b d8'          '8b 888888888 88  ##\n"
    printf "${blue}##                                              ##\n"
    printf "${blue}##                 arm64-v8a by KhanhNguyen9872 ##\n"
    printf "${blue}##################################################${reset}\n\n"
}

function installapp_khanh() {
    wget -O audio.apk "https://github.com/KhanhNguyen9872/Kali-Linux-aarch64-arm64-/blob/main/app/Audio.apk?raw=true"
    wget -O micro.apk "https://github.com/KhanhNguyen9872/Kali-Linux-aarch64-arm64-/blob/main/app/Micro.apk?raw=true"
    clear
    echo ""
    printf " Installing Audio app....."
    echo ""
    termux-open audio.apk
    rm -f audio.apk
    printf " Installing Micro app....."
    echo ""
    termux-open micro.apk
    rm -f micro.apk
}

##################################
##              Main            ##

red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'
reset='\033[0m'

EXTRA_ARGS=""
if [[ ! -z $1 ]]; then
    EXTRA_ARGS=$1
    if [[ $EXTRA_ARGS != "--insecure" ]]; then
        EXTRA_ARGS=""
    fi
fi

cd $HOME
print_banner
get_arch
set_strings
prepare_fs
check_dependencies
get_rootfs
get_sha
verify_sha
extract_rootfs
create_launcher
cleanup

printf "\n${blue}[*] Dang config Kali-Linux (arm64)....\n"
fix_profile_bash
fix_sudo
create_kex_launcher
fix_uid
installapp_khanh

print_banner
printf "${yellow}[=] Kali-Linux KhanhNguyen da duoc cai dat${reset}\n\n"
printf "${red}[@] Password VNC:  khanhnguyen ${reset}\n"
printf "${red}[@] Password su:   khanhnguyen ${reset}\n"
printf "${light_cyan} Github: https://github.com/khanhnguyen9872${reset}\n"
printf "%b\n" " "
printf "${green}[+] Thong tin lenh, type:${reset}\n"
printf "${green}[+] kali                  # Start Kali-Linux chroot${reset}\n"
printf "${green}[+] kali khanh            # Start Kali-Linux VNC Viewer${reset}\n"
printf "${green}[+] kali khanh stop       # Stop Kali-Linux VNC Viewer${reset}\n"
printf "${green}[+] kali su               # Run Kali-Linux as root user${reset}\n"
printf "${green}[+] kali khanhnguyen9872  # Get Information this Kali-Linux${reset}\n"
printf "${green}[+] recovery              # Run Recovery Mode${reset}\n\n"
rm -f ~/install-kali-khanhnguyen
exit 0
