#!/data/data/com.termux/files/usr/bin/bash -e
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'
reset='\033[0m'
clear
cd
cd ..
khanh=usr/bin/khanh
if [ -f $khanh ]; then
	left=4
	khanh1="$(grep '' './usr/bin/khanh')"
	while [[ $left -eq 4 ]] || [[ $left -eq 3 ]] || [[ $left -eq 2 ]] || [[ $left -eq 1 ]]; do
		clear
		if [[ $wrong -eq 1 ]]; then
			printf "\n ${red} - Wrong Password! $left attempts left! ${reset}\n\n"
		fi
		if [[ $left -eq 0 ]]; then
			clear
			printf "\n\n ${red} - Wrong Password! Exit! ${reset}\n\n"
			exit 0
		fi
		printf "${light_cyan}\n   Type your Password! ${reset}\n\n"
		read -p "Password: " anykey
		if [[ $anykey -eq $khanh1 ]] 2> /dev/null || [ $anykey = $khanh1 ] 2> /dev/null; then
			printf "\n ${yellow} - PASS! ${reset}\n"
			newpass=1
			break
		else
			wrong=1
			left=$((left-1))
		fi
	done
	if [[ $left -eq 0 ]]; then
		clear
		printf "\n\n ${red} - Wrong Password! Exit! ${reset}\n\n"
		exit 0
	fi
fi
clear
printf "\033[1;34m##################################################\n"
printf "\033[1;34m##                                              ##\n"
printf "\033[1;34m##  88      a8P         db        88        88  ##\n"
printf "\033[1;34m##  88    .88'         d88b       88        88  ##\n"
printf "\033[1;34m##  88   88'          d8''8b      88        88  ##\n"
printf "\033[1;34m##  88 d88           d8'  '8b     88        88  ##\n"
printf "\033[1;34m##  8888'88.        d8YaaaaY8b    88        88  ##\n"
printf "\033[1;34m##  88P   Y8b      d8''''''''8b   88        88  ##\n"
printf "\033[1;34m##  88     '88.   d8'        '8b  88        88  ##\n"
printf "\033[1;34m##  88       Y8b d8'          '8b 888888888 88  ##\n"
printf "\033[1;34m##                                              ##\n"
printf "\033[1;34m##                 arm64-v8a by KhanhNguyen9872 ##\n"
printf "\033[1;34m##################################################\033[0m\n\n"
printf "\033[1;33m[=] Kali-Linux KhanhNguyen (Thanks<3)\033[0m\n\n"
printf "\033[1;31m[@] Password VNC:  khanhnguyen \033[0m\n"
printf "\033[1;31m[@] Password su:   khanhnguyen \033[0m\n"
printf "\033[1;31m[@] Password sudo: khanhnguyen \033[0m\n\n"
printf "\033[1;32m[+] Thong tin lenh, type:\033[0m\n"
printf "\033[1;32m[+] khanh            # Start Kali-Linux VNC Viewer\033[0m\n"
printf "\033[1;32m[+] khanh stop       # Stop Kali-Linux VNC Viewer\033[0m\n"
printf "\033[1;32m[+] su               # Run Kali-Linux as root user\033[0m\n"
printf "\033[1;32m[+] khanhnguyen9872  # Get Information this Kali-Linux\033[0m\n"
printf "\033[1;32m[+] recovery         # Run Recovery Mode\033[0m\n\n"
cd ${HOME}
unset LD_PRELOAD
if [ ! -f kali-arm64/root/.version ]; then
    touch kali-arm64/root/.version
fi

user="kali"
home="/home/$user"
start="sudo -u kali /bin/bash"

if grep -q "kali" kali-arm64/etc/passwd; then
    KALIUSR="1";
else
    KALIUSR="0";
fi
if [[ $KALIUSR == "0" || ("$#" != "0" && ("$1" == "-r" || "$1" == "-R")) ]];then
    user="root"
    home="/$user"
    start="/bin/bash --login"
    if [[ "$#" != "0" && ("$1" == "-r" || "$1" == "-R") ]];then
        shift
    fi
fi

cmdline="proot \
        --link2symlink \
        -0 \
        -r kali-arm64 \
        -b /dev \
        -b /data \
        -b /vendor \
        -b /product \
        -b /mnt \
        -b /storage \
        -b /sdcard \
        -b /system \
        -b /proc \
        -b kali-arm64$home:/dev/shm \
        -w $home \
           /usr/bin/env -i \
           HOME=$home \
           PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \
           TERM=$TERM \
           LANG=C.UTF-8 \
           $start"

cmd="$@"
if [ "$#" == "0" ];then
    exec $cmdline
else
    $cmdline -c "$cmd"
fi
