#!/data/data/com.termux/files/usr/bin/bash -e

VERSION=20211012
USERNAME="kali"
IMAGE_NAME=$restoreimage
SHA_NAME=$sha512sumfile
CHROOT=kali-arm64

function ask() {
    while true; do

        if [ "${2:-}" = "Y" ]; then
            prompt="Y/n"
            default=Y
        elif [ "${2:-}" = "N" ]; then
            prompt="y/N"
            default=N
        else
            prompt="y/n"
            default=
        fi

        printf "${light_cyan}\n[?] "
        read -p "$1 [$prompt] " REPLY

        if [ -z "$REPLY" ]; then
            REPLY=$default
        fi

        printf "${reset}"

        case "$REPLY" in
            Y*|y*) return 0 ;;
            N*|n*) return 1 ;;
        esac
    done
}

function check_dependencies() {
    printf "${blue}\n[*] Dang kiem tra....${reset}\n"
    apt-get update -y &> /dev/null || apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confnew" dist-upgrade -y &> /dev/null
    apt-get upgrade -y &> /dev/null
    printf "${blue}[*] - Done ${reset}\n"
}


function get_url() {
    ROOTFS_URL="https://tinyurl.com/nx64mce5"
    SHA_URL="https://tinyurl.com/xb7jsx2x"
}

function extract_rootfs() {
        printf "\n${blue}[*] Restoring image..... ${reset}\n"
	cd $HOME
        proot --link2symlink tar -xf /sdcard/$IMAGE_NAME 2> /dev/null || : && echo "- Done"
}


function create_launcher() {
	mv ~/khanh ~/kali-arm64/usr/bin 2> /dev/null || :
	chmod 777 ~/kali-arm64/usr/bin/khanh 2> /dev/null || :
    KH_RECOVERY=$HOME/kali-arm64/usr/bin/recovery
    NH_LAUNCHER=${PREFIX}/bin/kali
    NH_SHORTCUT=${PREFIX}/bin/nh
    KEX_LAUNCHER=$HOME/kali-arm64/usr/bin/khanh
    cat > $NH_LAUNCHER <<- EOF
#!/data/data/com.termux/files/usr/bin/bash -e
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'
reset='\033[0m'
clear
printf "${blue}##################################################\n"
printf "${blue}##                                              ##\n"
printf "${blue}##  88      a8P         db        88        88  ##\n"
printf "${blue}##  88    .88'         d88b       88        88  ##\n"
printf "${blue}##  88   88'          d8''8b      88        88  ##\n"
printf "${blue}##  88 d88           d8'  '8b     88        88  ##\n"
printf "${blue}##  8888'88.        d8YaaaaY8b    88        88  ##\n"
printf "${blue}##  88P   Y8b      d8''''''''8b   88        88  ##\n"
printf "${blue}##  88     '88.   d8'        '8b  88        88  ##\n"
printf "${blue}##  88       Y8b d8'          '8b 888888888 88  ##\n"
printf "${blue}##                                              ##\n"
printf "${blue}##                 arm64-v8a by KhanhNguyen9872 ##\n"
printf "${blue}##################################################${reset}\n\n"
printf "${yellow}[=] Kali-Linux KhanhNguyen (Thanks<3)${reset}\n\n"
printf "${red}[@] Password VNC:  khanhnguyen ${reset}\n"
printf "${red}[@] Password su:   khanhnguyen ${reset}\n"
printf "${red}[@] Password sudo: khanhnguyen ${reset}\n\n"
printf "${green}[+] Thong tin lenh, type:${reset}\n"
printf "${green}[+] khanh            # Start Kali-Linux VNC Viewer${reset}\n"
printf "${green}[+] khanh stop       # Stop Kali-Linux VNC Viewer${reset}\n"
printf "${green}[+] su               # Run Kali-Linux as root user${reset}\n"
printf "${green}[+] khanhnguyen9872  # Get Information this Kali-Linux${reset}\n"
printf "${green}[+] recovery         # Run Recovery Mode${reset}\n\n"
cd \${HOME}
unset LD_PRELOAD
if [ ! -f $CHROOT/root/.version ]; then
    touch $CHROOT/root/.version
fi

user="$USERNAME"
home="/home/\$user"
start="sudo -u kali /bin/bash"

if grep -q "kali" ${CHROOT}/etc/passwd; then
    KALIUSR="1";
else
    KALIUSR="0";
fi
if [[ \$KALIUSR == "0" || ("\$#" != "0" && ("\$1" == "-r" || "\$1" == "-R")) ]];then
    user="root"
    home="/\$user"
    start="/bin/bash --login"
    if [[ "\$#" != "0" && ("\$1" == "-r" || "\$1" == "-R") ]];then
        shift
    fi
fi

cmdline="proot \\
        --link2symlink \\
        -0 \\
        -r $CHROOT \\
        -b /dev \\
        -b /sdcard \\
	-b /system \\
        -b /proc \\
        -b $CHROOT\$home:/dev/shm \\
        -w \$home \\
           /usr/bin/env -i \\
           HOME=\$home \\
           PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \\
           TERM=\$TERM \\
           LANG=C.UTF-8 \\
           \$start"

cmd="\$@"
if [ "\$#" == "0" ];then
    exec \$cmdline
else
    \$cmdline -c "\$cmd"
fi
	EOF
	
	cat > $KH_RECOVERY <<- EOF
##!/data/data/com.termux/files/usr/bin/bash -e
red='\033[1;31m'
printf "%b\n" "${red}\n Please exit Kali-Linux and run 'recovery' in Termux \n\n"
	EOF

    chmod 777 $NH_LAUNCHER
    chmod 777 $KH_RECOVERY
    chmod 777 $KEX_LAUNCHER
    if [ -L ${NH_SHORTCUT} ]; then
        rm -f ${NH_SHORTCUT}
    fi
    if [ ! -f ${NH_SHORTCUT} ]; then
        ln -s ${NH_LAUNCHER} ${NH_SHORTCUT} >/dev/null
    fi
}

function fix_profile_bash() {
    if [ -f ${CHROOT}/root/.bash_profile ]; then
        sed -i '/if/,/fi/d' "${CHROOT}/root/.bash_profile"
    fi
}

function fix_sudo() {
    chmod +s $CHROOT/usr/bin/sudo
    chmod +s $CHROOT/usr/bin/su
	echo "kali    ALL=(ALL:ALL) ALL" > $CHROOT/etc/sudoers.d/kali

    echo "Set disable_coredump false" > $CHROOT/etc/sudo.conf
}

function fix_uid() {
    USRID=$(id -u)
    GRPID=$(id -g)
    nh -r usermod -u $USRID kali 2>/dev/null
    nh -r groupmod -g $GRPID kali 2>/dev/null
}


##################################
##              Main            ##

red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'
reset='\033[0m'

EXTRA_ARGS=""
if [[ ! -z $1 ]]; then
    EXTRA_ARGS=$1
    if [[ $EXTRA_ARGS != "--insecure" ]]; then
        EXTRA_ARGS=""
    fi
fi

cd $HOME
check_dependencies
extract_rootfs
create_launcher
fix_profile_bash
fix_sudo
create_kex_launcher
fix_uid

printf "${blue} Restore completed! ${reset}\n\n"
rm -f ~/restore-image
