#!/data/data/com.termux/files/usr/bin/bash -e
red='\033[1;31m'
green='\033[1;32m'
yellow='\033[1;33m'
blue='\033[1;34m'
light_cyan='\033[1;96m'
reset='\033[0m'
sshd
user="$(whoami)"
clear
printf "${yellow}\n Type your password!\n"
passwd ${user}
printf "\n\n"
ifconfig | grep 'inet'
printf "${light_cyan}\n\n Use this command for connect:\n"
printf "ssh ${user}@[YourIP] -p 8022\n\n"
