#!/data/data/com.termux/files/usr/bin/bash -e
red='\033[1;31m' 2> /dev/null
green='\033[1;32m' 2> /dev/null
yellow='\033[1;33m' 2> /dev/null
blue='\033[1;34m' 2> /dev/null
light_cyan='\033[1;96m' 2> /dev/null
reset='\033[0m' 2> /dev/null
sshd 2> /dev/null
user="$(whoami)" 2> /dev/null
cd ../usr/etc 2> /dev/null
if [ -f passwd ] 2> /dev/null; then
	clear
else
	clear
	printf "${yellow}\n Type your password!\n"
	passwd ${user}
	echo 'khanh' > passwd
fi
cd 2> /dev/null
printf "\n\n"
ifconfig | grep 'inet'
printf "${light_cyan}\n\n Use this command for connect:\n"
printf "ssh ${user}@[YourIP] -p 8022\n\n"
