#!/usr/bin/bash
#khanhnguyen9872
light='\033[1;96m'
red='\033[1;31m'
yellow='\033[1;33m'
reset='\033[0m'
printf "%b\n" "${yellow} "
printf "%b\n" "Nguyen Van Khanh (KhanhNguyen9872)"
printf "%b\n" "Facebook: https://fb.me/khanh10a1"
printf "%b\n" "Instagram: khanh10a1"
printf "%b\n" "Github: https://github.com/khanhnguyen9872"
printf "%b\n" "Youtube: https://tinyurl.com/khanhvuinguyenvan9872"
printf "%b\n" "${red} "
printf "%b\n" " @ Kali-Linux (arm64-v8a) on Termux @"
printf "%b\n" "   @@ Thanks for used! @@"
printf "%b\n" "${reset} "
printf "%b\n" " * Changelogs:${light}"
printf "%b\n" " - Add ARMCORD [Discord] (arm64)"
printf "%b\n" " - Add ZOOM Cloud Meetings (i386)"
printf "%b\n" " - Add VirtualMIC"
printf "%b\n" " - Add Ethernet, Volume Control in taskbar"
printf "%b\n" " - Add Box86, Box64"
printf "%b\n" " - Supported armhf packages"
printf "%b\n" " - Add VNC Viewer (armhf)"
printf "%b\n" " - Fixed Systemctl"
printf "%b\n" " - Add run Debian 9 (i386)"
printf "%b\n" " - Debian can run as User or Root"
printf "%b\n" " - Add LibreOffice (arm64) [Fixed runtime]"
printf "%b\n" " - Make look like Windows 10"
printf "%b\n" " - Remove postgresql,blueman,clipman,vim,catfish,..."
printf "%b\n" " - Remove Orca for disable speech text"
printf "%b\n" " - Disable some task when startup"
printf "%b\n" " - Remove Firefox-ESR"
printf "%b\n" " - PulseAudio now available (arm64)"
printf "%b\n" " - Visual Code (arm64) [Fixed: Not running]"
printf "%b\n" " - Ibus-unikey (arm64) [Unikey Keyboard]"
printf "%b\n" " - Sublime Text (arm64) [Add License]"
printf "%b\n" " - Task Manager (arm64) [Check Process, CPU/RAM usage]"
printf "%b\n" " - Hardinfo (arm64) [Type "hardinfo" in Terminal to check SystemInfo]"
printf "%b\n" " - Python3.9 + IDLE Python 3.10 (arm64)"
printf "%b\n" " - Chromium (arm64) [Supported: Render 3D]"
printf "%b\n" " - Add MESA [llvmpipe (LLVM 12.0.1, 128 bits) - OpenGL 3.1 Mesa 21.2.6]"
printf "%b\n" " - Enable Hardware Rendering (Direct Rendering)"
printf "%b\n" " - All Package updated on 23/12/2021"
printf "%b\n" " - Remove Application not used for increase free space and Performance"
printf "%b\n" " - Change other Wallpaper Windows 10 ${reset}"
 
